#!/bin/bash

# block rw testing in nondestructive mode
# give it a device and it will go after it


if [ -z "$2" ] ; then
    echo device bsize required
    exit 2
fi

bsize=$2

./bin/flushb $1
nice -n 5 badblocks -n -b $bsize $1 
exit $?
